```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(ggplot2)
library(readr)
library(ggrepel)
library(magrittr)
library(dplyr)
library(tidyr)
library(gridExtra)
library(cowplot)
library(glue)
# library("grid")
library(ribd)
# library("ggplotify")



# library(tidyverse)
```

```{r}
getwd()
```

```{r}
# setwd('results/relate')
data <- read.table('A_2.txt', header=TRUE)

#create vertical side-by-side boxplots
boxplot(data$rmse ~ data$deamination,
        col='steelblue',
        main='Points by Team',
        xlab='Team',
        ylab='Points')
```

## PLot KING-R1
```{r}
setwd("./Pedigree_19/Coverage_2/no_deam/ngsrelate")
```
```{r}
res <- read.table("ngsrelate.no_deam.ped19.reads2x.res.correct", header=TRUE)
res$name <- paste(res$a,'-',res$b)
options(ggrepel.max.overlaps = Inf)

(g <- ggplot(res, aes(x = R1, y = KING)) + 
    geom_point(color = "firebrick", shape = "diamond", size = 2)) +
    # geom_text(hjust=0, vjust=0) +
    geom_label_repel(aes(label = name),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50')

# ggsave("ped19_2x.png")


### or by removing the individuals that don't interfeere with the predigree at all (to make the plot cleaner)
res %>%
    filter(!res$a %in% c(12, 13, 14, 16 )) %>%
    filter(., !b %in% c(12, 13, 14, 16 )) -> coisa


# coisa$name <- paste(coisa$a,'-',coisa$b)

(g <- ggplot(coisa, aes(x = R1, y = KING)) + 
    geom_point(color = "firebrick", shape = "diamond", size = 2)) +
    # geom_text(hjust=0, vjust=0) +
    geom_label_repel(aes(label = name),
                  box.padding   = 0.35, 
                  point.padding = 0.5,
                  segment.color = 'grey50')
```


## PLot K0,k1,k2 according to coverage
```{r}
# setwd(".")
getwd()
```
### for ngsrelate that uses original derived frequencies as input 
```{r}
# take ped1,2,3 cov2,4

res <- read.csv("results2/relate/ngsresults.final", header=TRUE, sep="\t")
rownames(res) <- NULL

res %>%
    filter(., related != 'related') %>%
    ggplot(., aes(x=cov, y=as.numeric(as.character(J9)), fill= cov )) +
        geom_boxplot() + 
        xlab("coverage") +
        ylab('K0') +
        ggtitle("Results using original derived frequency for 20 simulations") -> g
hh <- g + facet_wrap(~ related, ncol=4)
hh    

# ggsave("ngsrelate_results/ngsrelate2_k2.png")

```

### for ngsrelate that uses angsd maf.gz frequencies as input 
```{r}
res <- read.csv("ngsrelate_results/ngsrelate_cov2_4._pedAll_angsd_freq.csv", header=TRUE, sep="\t")
rownames(res) <- NULL

res %>%
    filter(., related != 'related') %>%
    ggplot(., aes(x=cov, y=as.numeric(as.character(J7)), fill= cov )) +
        geom_boxplot() + 
        xlab("coverage") +
        ylab('K2') +
        ggtitle("Results using angsd frequency for 20 simulations") -> g
gg <- g + facet_wrap(~ related, ncol=4)
gg 

ggsave("ngsrelate_results/ngsrelate_k2.png")
```

## Plot histogram of maf frequencies
```{r}
setwd('/maps/projects/korneliussen/people/vlr112/simulations3/Pedigree_3/Coverage_4/no_deam/ngsrelate2/')

# d <- read.table("angsdput2.mafs.gz",he=T)
# # hist(d$knownEM)

# pdf("Ped3_cov4.mafs.pdf")
# hist(d$knownEM)
# dev.off()

d <- read.table("final_freq",he=F)
final_freq <- as.data.frame(d)

# hist(coisa$V1)

pdf("Original_derived_freq.hist.pdf")
hist(final_freq$V1)
dev.off()

```

## clean dataframe so plot is like the one in the ngsrelate paper

```{r}
k0 <- c(0.75, 0.75, 0.75, 0, 0.875, 0.25, 0.5, 0.1)
k1 <- c(0.25, 0.25, 0.25, 1, 0.125, 0.5, 0.5, 0)
k2 <- c(0,0,0,0,0,0.25, 0,0)
relationship <- c('firstcousin', 'Grandschild', 'great-uncle-nephew', 'PO', 'removed1cousins', 'sibs', 'Uncle-nephew', 'Unrelated')

df <- data.frame(relationship, k0, k1, k2)
  
```


```{r}
res <- read.csv("ngsrelate_results/ngsrelate_cov2_4_pedAll.csv", header=TRUE, sep="\t")

df3 <- merge(res, df, by.x=c('related'), by.y=c("relationship"))


df3 %>%
    filter(., related != 'related') %>%
    mutate(K0 = as.numeric(J9) - k0) %>%
    mutate(K1 = as.numeric(J8) - k1) %>%
    mutate(K2 = as.numeric(J7) - k2) %>%
    ggplot(., aes(x=cov, y=as.numeric(as.character(K2)), fill= cov )) +
        geom_boxplot() + 
        geom_hline(aes(yintercept = 0, colour = 'red')) +
        xlab("coverage") +
        ylab('K2') +
        ggtitle("Results using original derived frequency for 20 simulations") -> g
gg <- g + facet_wrap(~ related, ncol=4)
gg 

ggsave("ngsrelate_results/ngsrelate2_allPed_k2.png")
```

### for ngsrelate that uses original frequencies as input and has cov10 also. Plot by kin
```{r}
# res <- read.csv("ngsrelate_results/coisa.csv", header=TRUE, sep="\t")
res <- read.csv("results2/relate/ngsresults.final", header=TRUE, sep="\t")

rownames(res) <- NULL

my_plot <- function(J7, k2, relative){

    # res$cov <- factor(res$ped)

    res %>%
        filter(., related != 'related') %>%
        filter(., related == relative) %>%
        ggplot(., aes( y=as.numeric({{J7}}))) +
            geom_boxplot() + 
            xlab("coverage") +
            ylab(glue('{k2}')) -> g
            # ggtitle("Results using angsd frequency for 20 simulations") -> g
    # gg <- g + facet_wrap(~ related, ncol=4)
    return(g)

}

final_plot <- function(relative){

    # title <- ggdraw() + draw_label(relative, fontface='bold', colour= 'red')
    plot_grid( my_plot(J9, "k0", relative), labels = relative, ncol = 1) -> coisa
    # ggsave(glue("ngsrelate_results/ngsrelate2_{relative}.png"))
    # save_plot("ngsrelate_results/ngsrelate2_{relative}.png", coisa)
    return(coisa)
}

final_plot("Unrelated")

# ggsave("ngsrelate_results/ngsrelate_k2.png")
```

## Plot R1/R0/King

```{r}
res <- read.csv("results2/relate/ngsresults.final", header=TRUE, sep="\t")

my_plot_king <- function(xx, X, yy , Y){
    res %>% 
        filter(., related != 'related') %>%
        # filter(., related == 'PO') %>%
        # filter(., cov == as.numeric(my_cov)) %>%
        ggplot(aes(x = as.numeric({{xx}}), y = as.numeric({{yy}})) + 
            geom_point( color = (related)),
                shape = "diamond", size = 2)  +
                xlab(glue('{X}')) +
                ylab(glue('{Y}')) ->g
            # xlab(as.character(xx)) +
            # ylab(glue("{y}"))-> g
        return(g)

}
my_plot_king(R1, "R1", R0, "R0"  )

# (g <- ggplot(res, aes(x = R1, y = KING)) + 
#     geom_point(color = "firebrick", shape = "diamond", size = 2)) +
#     # geom_text(hjust=0, vjust=0) +
#     geom_label_repel(aes(label = name),
#                   box.padding   = 0.35, 
#                   point.padding = 0.5,
#                   segment.color = 'grey50')


final_plot_king <- function(){

    # title <- ggdraw() + draw_label(relative, fontface='bold', colour= 'red')
    # plot_grid(my_plot_king(R1, "R1", R0, "R0"  ), my_plot_king(R1, "R1", KING, "KING"),  ncol = 1) -> coisa
    # ggsave(glue("ngsrelate_results/R_KING_{cc}x.png"))
    # save_plot("ngsrelate_results/ngsrelate2_{relative}.png", coisa)
    return(coisa)
}
my_plot_king(R1, "R1", R0, "R0"  )# label = glue('Coverage {cov} x')
final_plot_king()

```

```{r}
res <- read.csv("results2/relate/ngsresults.final", header=TRUE, sep="\t")
rownames(res) <- NULL

res %>%
    filter(., related != 'related') %>%
    filter(., related == 'PO') %>%
    # head(.)
    boxplot(J9)
#     ggplot(., aes(x=cov, y=as.numeric(as.character(J7)), fill= cov )) +
#         geom_boxplot() + 
#         xlab("coverage") +
#         ylab('K2') +
#         ggtitle("Results using angsd frequency for 20 simulations") -> g
# gg <- g + facet_wrap(~ related, ncol=4)
# gg 

# ggsave("ngsrelate_results/ngsrelate_k2.png")
```


```{r}
# to write an existing table `snp` into file "data.snp", run like this:
# write_snp("data", snp)
# this also works
# write_snp("data.snp", snp)

# The following example is more detailed but also more awkward
# because (only for these examples) the package must create the file in a *temporary* location
library(genio)
# create a dummy tibble with the right columns
library(tibble)
tib <- tibble(
    id = 1:3,
    chr = 1:3,
    posg = 0,
    pos = 1:3,
    ref = 'A',
    alt = 'B'
)
# a dummy file
file_out <- tempfile('delete-me-example', fileext = '.snp') # will also work without extension
# write the table out in *.snp format (no header, columns in right order)
write_snp("data.snp", tib)
# delete output when done
# file.remove(file_out)
```

```{r}
print(data.spn)
```